"""Generate data/synthetic_fixture.csv.

THIS PRODUCES FAKE DATA. It exists only so the pipeline and tests can run
without licensed PitchBook data. Funding follows a seeded AR(1) process in
logs with a sector-specific level and a mild common cycle; deal counts are
Poisson around a sector-specific mean. Nothing here is derived from, or
planted to correlate with, real market returns.
"""
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "synthetic_fixture.csv"
SEED = 0

SECTOR_LEVELS_USD_BN = {   # rough order-of-magnitude quarterly VC volume, made up
    "software": 25, "cybersecurity": 5, "biotech": 12, "semiconductors": 3,
    "fintech": 10, "technology": 30, "healthcare": 15, "financials": 6,
    "energy": 4, "industrials": 5,
}
DEAL_MEANS = {
    "software": 900, "cybersecurity": 150, "biotech": 350, "semiconductors": 80,
    "fintech": 400, "technology": 1200, "healthcare": 600, "financials": 200,
    "energy": 120, "industrials": 180,
}


def main() -> None:
    rng = np.random.default_rng(SEED)
    quarters = pd.period_range("2014Q1", "2026Q2", freq="Q")
    n = len(quarters)
    common = np.zeros(n)
    for t in range(1, n):
        common[t] = 0.8 * common[t - 1] + rng.normal(0, 0.10)

    rows = []
    for sector, level in SECTOR_LEVELS_USD_BN.items():
        own = np.zeros(n)
        for t in range(1, n):
            own[t] = 0.6 * own[t - 1] + rng.normal(0, 0.25)
        log_funding = np.log(level * 1e9) + common + own
        funding = np.exp(log_funding)
        deals = rng.poisson(DEAL_MEANS[sector] * np.exp(0.5 * (common + own)))
        median_val = np.exp(np.log(60e6) + 0.3 * (common + own) + rng.normal(0, 0.15, n))
        for q, f, d, v in zip(quarters, funding, deals, median_val):
            rows.append({
                "sector": sector,
                "quarter": str(q),
                "total_funding_usd": round(float(f), 0),
                "deal_count": int(d),
                "median_valuation_usd": round(float(v), 0),
            })

    df = pd.DataFrame(rows)
    header = (
        "# SYNTHETIC FIXTURE -- FAKE DATA -- generated by scripts/make_synthetic_fixture.py "
        f"(seed={SEED}). No relationship to real funding or returns. Do not interpret.\n"
    )
    OUT.parent.mkdir(exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header)
        df.to_csv(fh, index=False)
    print(f"wrote {OUT} ({len(df)} rows, {df['sector'].nunique()} sectors, {n} quarters)")


if __name__ == "__main__":
    main()
